version: '3.8'

services:
  diami-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diami-bot
    network_mode: 'default'
    restart: unless-stopped
    volumes:
      - app:/app/data
    tty: true
    env_file:
      - .env